<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Parasite SEO Engine.
 *
 * Repurposes published WP posts for external platforms (Medium, LinkedIn,
 * Quora, Reddit, generic). Each platform has a distinct rewrite strategy
 * because the SEO and compliance rules differ sharply:
 *
 *   - Medium  → supports rel=canonical. Can be full-length faithful rewrite.
 *   - LinkedIn → NO canonical. Must be substantially rewritten so it
 *                doesn't compete with the original for the same query.
 *   - Quora    → Answers a SPECIFIC question, first-person, link in source.
 *   - Reddit   → Native summary only, never the full article. 9:1 rule
 *                compliance warning surfaced to the user.
 *   - Generic  → Customizable wrapper for any other platform.
 *
 * Output is generated by Claude given a tightly-scoped per-platform system
 * prompt. Each generation is stored in the syndications log so the admin
 * can copy → paste into the platform UI, then mark "published" with the
 * external URL.
 */
class RankWriter_AI_Parasite_Engine {

	const PLATFORM_MEDIUM   = 'medium';
	const PLATFORM_LINKEDIN = 'linkedin';
	const PLATFORM_QUORA    = 'quora';
	const PLATFORM_REDDIT   = 'reddit';
	const PLATFORM_GENERIC  = 'generic';

	public static function platforms() {
		return array(
			self::PLATFORM_MEDIUM => array(
				'label'            => __( 'Medium', 'rankwriter-ai' ),
				'strategy'         => 'rewrite',
				'target_words'     => 1800,
				'min_words'        => 1200,
				'max_words'        => 2400,
				'canonical_safe'   => true,
				'allows_hashtags'  => true,
				'cta_position'     => 'bottom',
				'compliance'       => __( 'Medium SUPPORTS rel=canonical. Use Story Settings → "Add canonical link" pointing to your blog post. With canonical set, Google attributes ranking to your blog, not Medium.', 'rankwriter-ai' ),
				'system_prompt'    => 'You are repurposing an article for Medium.com. RULES: Write a faithful, slightly-shortened version (1500-2200 words). Hook the reader in the first 2 sentences. Use H2 subheadings every 200-300 words. Short paragraphs (2-3 sentences max). Add ONE strong opinion or counterintuitive insight the original may have understated. End with a clear CTA pointing back to the canonical source.',
			),
			self::PLATFORM_LINKEDIN => array(
				'label'            => __( 'LinkedIn Articles', 'rankwriter-ai' ),
				'strategy'         => 'rewrite',
				'target_words'     => 1000,
				'min_words'        => 700,
				'max_words'        => 1500,
				'canonical_safe'   => false,
				'allows_hashtags'  => true,
				'cta_position'     => 'bottom',
				'compliance'       => __( 'LinkedIn does NOT support rel=canonical. The rewrite must be substantively different from your blog post (30%+ new phrasing, new intro, reordered structure) or you risk duplicate-content competing with your own URL.', 'rankwriter-ai' ),
				'system_prompt'    => 'You are repurposing an article for LinkedIn. RULES: This is a professional-network audience — write in first person and lead with a personal stake or business insight in the first sentence. The structure MUST differ from the original (different intro angle, different ordering of key points). Target 800-1200 words. Use 4-6 short subheadings. End with a single question to the reader to drive comments. Append 3-5 industry-relevant hashtags. CRITICAL: this rewrite must NOT be a paraphrase — it should be a fresh angle on the same expertise.',
			),
			self::PLATFORM_QUORA => array(
				'label'            => __( 'Quora', 'rankwriter-ai' ),
				'strategy'         => 'qa',
				'target_words'     => 600,
				'min_words'        => 350,
				'max_words'        => 900,
				'canonical_safe'   => false,
				'allows_hashtags'  => false,
				'cta_position'     => 'bottom',
				'compliance'       => __( 'Quora is question-specific. You must find or paraphrase a real Quora question your post answers, then write a fresh answer. Don\'t paste the article — Quora\'s ranking ignores duplicates and self-promotion gets flagged. End with a brief, factual link reference, not a sales pitch.', 'rankwriter-ai' ),
				'system_prompt'    => 'You are repurposing an article into a Quora answer. RULES: Start with the specific question being answered, then a 1-sentence summary, then a first-person practitioner answer (~500 words). Use natural paragraph breaks, NO H1/H2 — Quora answers are prose. Lead with personal experience or specific data. End with one short paragraph: "For the longer breakdown including [specific extra angle the answer didn\'t cover], I wrote a fuller piece here: [LINK]" — factual, not promotional.',
			),
			self::PLATFORM_REDDIT => array(
				'label'            => __( 'Reddit Summary', 'rankwriter-ai' ),
				'strategy'         => 'summary',
				'target_words'     => 300,
				'min_words'        => 150,
				'max_words'        => 500,
				'canonical_safe'   => false,
				'allows_hashtags'  => false,
				'cta_position'     => 'bottom_soft',
				'compliance'       => __( 'Reddit enforces a 9:1 ratio (9 non-promotional posts/comments for every 1 link to your own content) and most subreddits ban link-only self-promotion outright. Read the target sub\'s rules before posting. This output is a SUMMARY, not the full article — a Reddit post that\'s clearly a blog dump will be removed.', 'rankwriter-ai' ),
				'system_prompt'    => 'You are repurposing an article for Reddit. RULES: Write as a redditor, not a marketer. Start with a "TL;DR:" line under 30 words. Then 2-3 short paragraphs of the most useful, native, slightly-opinionated takeaways (~250 words total). NO marketing voice, NO hashtags, NO promotional framing. End with one neutral line: "Full writeup with sources: [LINK]". Suggest 2-3 specific subreddit names where this would be appropriate (in a "Suggested subreddits:" line at the very end).',
			),
			self::PLATFORM_GENERIC => array(
				'label'            => __( 'Generic / External', 'rankwriter-ai' ),
				'strategy'         => 'rewrite',
				'target_words'     => 1200,
				'min_words'        => 600,
				'max_words'        => 2500,
				'canonical_safe'   => true,
				'allows_hashtags'  => false,
				'cta_position'     => 'bottom',
				'compliance'       => __( 'Generic syndication wrapper. Confirm the destination platform supports rel=canonical before publishing — if it does, point it at your blog post URL. If not, treat as duplicate-content risk and rewrite substantively.', 'rankwriter-ai' ),
				'system_prompt'    => 'You are repurposing an article for a generic external publishing platform. RULES: Faithful but slightly trimmed rewrite (~1000 words). Standard H2 structure, short paragraphs, conversational professional tone. End with a CTA pointing back to the canonical source.',
			),
		);
	}

	public static function platform( $key ) {
		$all = self::platforms();
		return $all[ $key ] ?? null;
	}

	/* ============================ Generation ============================ */

	/**
	 * Generate a repurposed payload for a single post + platform via Claude.
	 *
	 * @return array|WP_Error
	 */
	public function generate( $post_id, $platform ) {
		$post = get_post( $post_id );
		if ( ! $post ) {
			return new WP_Error( 'rwai_no_post', __( 'Post not found.', 'rankwriter-ai' ) );
		}
		$cfg = self::platform( $platform );
		if ( ! $cfg ) {
			return new WP_Error( 'rwai_bad_platform', __( 'Unknown platform.', 'rankwriter-ai' ) );
		}
		if ( ! class_exists( 'RankWriter_AI_Claude_Client' ) ) {
			return new WP_Error( 'rwai_no_client', __( 'Claude client unavailable.', 'rankwriter-ai' ) );
		}
		$client = new RankWriter_AI_Claude_Client();
		if ( ! $client->is_configured() ) {
			return new WP_Error( 'rwai_no_key', __( 'Claude API key not configured.', 'rankwriter-ai' ) );
		}

		$permalink   = get_permalink( $post_id );
		$canonical   = $cfg['canonical_safe'] ? $permalink : '';
		$brand_voice = '';
		if ( class_exists( 'RankWriter_AI_Voice_Memory' ) ) {
			$cats        = wp_get_post_categories( $post_id );
			$brand_voice = ( new RankWriter_AI_Voice_Memory() )->to_prompt_context( ! empty( $cats ) ? (int) $cats[0] : 0 );
		}

		$system = $cfg['system_prompt'] . "\n\n"
			. "Audience: external readers who have never read your blog.\n"
			. "Original source URL (for the link/CTA): " . $permalink . "\n"
			. ( $canonical ? "Canonical URL is supported on this platform. The platform will be told to canonical-attribute to the source.\n" : "Canonical is NOT supported here — rewrite must differ substantively from the original.\n" )
			. ( $brand_voice ? "\n" . $brand_voice . "\n\n" : "\n" )
			. "Return ONLY a single valid JSON object with this exact shape (no markdown fences, no commentary):\n"
			. "{\n"
			. "  \"title\": \"<external-platform headline>\",\n"
			. "  \"body\": \"<full body, HTML or plain text appropriate to the platform>\",\n"
			. "  \"cta\": \"<single-sentence CTA pointing back to the source, with the URL inline>\",\n"
			. "  \"hashtags\": [\"<tag1>\", \"<tag2>\", \"<tag3>\"],\n"
			. "  \"compliance_notes\": \"<one-line callout of any platform rule the user should double-check before posting>\"\n"
			. "}";

		// Build a tight user prompt — title + clean body + target words.
		$body_text = wp_strip_all_tags( $post->post_content );
		// Cap input length to keep context window healthy.
		if ( str_word_count( $body_text ) > 3500 ) {
			$body_text = implode( ' ', array_slice( preg_split( '/\s+/', $body_text ), 0, 3500 ) ) . ' …';
		}

		$user = "Original title: " . $post->post_title . "\n\n"
			. "Original body:\n" . $body_text . "\n\n"
			. "Target word count for the repurposed version: ~" . (int) $cfg['target_words'] . " words (hard min " . (int) $cfg['min_words'] . ", hard max " . (int) $cfg['max_words'] . ").";

		$raw = $client->send( $system, array(
			array( 'role' => 'user', 'content' => $user ),
		) );
		if ( is_wp_error( $raw ) ) {
			return $raw;
		}
		$parsed = $this->parse_json( $raw );
		if ( ! is_array( $parsed ) || empty( $parsed['body'] ) ) {
			return new WP_Error( 'rwai_bad_response', __( 'Claude response could not be parsed.', 'rankwriter-ai' ) );
		}

		$hashtags = isset( $parsed['hashtags'] ) && is_array( $parsed['hashtags'] ) ? array_slice( array_map( 'sanitize_text_field', $parsed['hashtags'] ), 0, 8 ) : array();

		$payload = array(
			'title'             => sanitize_text_field( (string) ( $parsed['title'] ?? '' ) ),
			'body'              => wp_kses_post( (string) $parsed['body'] ),
			'cta'               => sanitize_text_field( (string) ( $parsed['cta'] ?? '' ) ),
			'hashtags'          => $hashtags,
			'compliance_notes'  => sanitize_text_field( (string) ( $parsed['compliance_notes'] ?? '' ) ),
			'canonical_url'     => $canonical,
			'platform'          => $platform,
		);

		// Save as a draft row in the syndication log.
		if ( class_exists( 'RankWriter_AI_Syndication_DB' ) ) {
			$payload['log_id'] = RankWriter_AI_Syndication_DB::insert( array(
				'post_id'            => (int) $post_id,
				'platform'           => $platform,
				'status'             => RankWriter_AI_Syndication_DB::STATUS_DRAFT,
				'canonical_used'     => $canonical ? 1 : 0,
				'generated_title'    => $payload['title'],
				'generated_body'     => $payload['body'],
				'generated_cta'      => $payload['cta'],
				'generated_hashtags' => wp_json_encode( $hashtags ),
				'compliance_notes'   => $payload['compliance_notes'],
			) );
		}

		return $payload;
	}

	/**
	 * Mark a previously-generated syndication as live, recording the
	 * external URL the user pasted in.
	 */
	public function mark_published( $log_id, $external_url ) {
		if ( ! class_exists( 'RankWriter_AI_Syndication_DB' ) ) {
			return false;
		}
		return RankWriter_AI_Syndication_DB::update( $log_id, array(
			'status'       => RankWriter_AI_Syndication_DB::STATUS_PUBLISHED,
			'external_url' => esc_url_raw( $external_url ),
			'published_at' => current_time( 'mysql' ),
		) );
	}

	public function delete_syndication( $log_id ) {
		if ( ! class_exists( 'RankWriter_AI_Syndication_DB' ) ) {
			return false;
		}
		return RankWriter_AI_Syndication_DB::delete( $log_id );
	}

	protected function parse_json( $raw ) {
		$raw = trim( (string) $raw );
		if ( '' === $raw ) { return null; }
		$decoded = json_decode( $raw, true );
		if ( is_array( $decoded ) ) { return $decoded; }
		if ( preg_match( '/\{.*\}/s', $raw, $m ) ) {
			$decoded = json_decode( $m[0], true );
			if ( is_array( $decoded ) ) { return $decoded; }
			$cleaned = stripslashes( $m[0] );
			$decoded = json_decode( $cleaned, true );
			if ( is_array( $decoded ) ) { return $decoded; }
		}
		return null;
	}
}
